// @ts-check
/**
 * This file is auto-generated by Supabase.
 * Do not edit manually.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          subscription_tier: 'free' | 'pro' | 'business';
          minutes_used: number;
          minutes_limit: number;
        };
        Insert: {
          id?: string;
          email: string;
          created_at?: string;
          subscription_tier?: 'free' | 'pro' | 'business';
          minutes_used?: number;
          minutes_limit?: number;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          subscription_tier?: 'free' | 'pro' | 'business';
          minutes_used?: number;
          minutes_limit?: number;
        };
      };
      transcriptions: {
        Row: {
          id: string;
          user_id: string;
          audio_url: string;
          status: 'processing' | 'completed' | 'failed';
          transcript_text: string | null;
          duration_seconds: number | null;
          language: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          audio_url: string;
          status?: 'processing' | 'completed' | 'failed';
          transcript_text?: string | null;
          duration_seconds?: number | null;
          language?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          audio_url?: string;
          status?: 'processing' | 'completed' | 'failed';
          transcript_text?: string | null;
          duration_seconds?: number | null;
          language?: string | null;
          created_at?: string;
        };
      };
      show_notes: {
        Row: {
          id: string;
          transcription_id: string;
          summary: string | null;
          timestamps: Json | null;
          key_takeaways: string[] | null;
          tags: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          transcription_id: string;
          summary?: string | null;
          timestamps?: Json | null;
          key_takeaways?: string[] | null;
          tags?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          transcription_id?: string;
          summary?: string | null;
          timestamps?: Json | null;
          key_takeaways?: string[] | null;
          tags?: string[] | null;
          created_at?: string;
        };
      };
      clips: {
        Row: {
          id: string;
          transcription_id: string;
          start_time: number;
          end_time: number;
          title: string | null;
          video_url: string | null;
          status: 'generating' | 'completed' | 'failed';
          created_at: string;
        };
        Insert: {
          id?: string;
          transcription_id: string;
          start_time: number;
          end_time: number;
          title?: string | null;
          video_url?: string | null;
          status?: 'generating' | 'completed' | 'failed';
          created_at?: string;
        };
        Update: {
          id?: string;
          transcription_id?: string;
          start_time?: number;
          end_time?: number;
          title?: string | null;
          video_url?: string | null;
          status?: 'generating' | 'completed' | 'failed';
          created_at?: string;
        };
      };
    };
  };
}
